server:
  port: 9095

spring:
  application:
    name: DOCTOR-SERVICE
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/lifeline
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
#FIle Upload Setting
  servlet:
    multipart:
      max-file-size: 100000000MB
      max-request-size: 100000000MB

#Eureka Client Set
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true